import {
  Truck, Smartphone, Wallet, Satellite, Wrench, BarChart3, Package, Container,
  Link2, Camera, Landmark, Briefcase, Shield, Store, Fuel, FileText, Banknote,
  Map, ClipboardList, Siren, HandHeart, Lamp, Coins, Lock, Clock, Phone, Users,
  CreditCard, Settings, Route, TrendingUp, Handshake, User, FolderOpen, Receipt,
  UserCog, Calculator, Sparkles, BookOpen, Search, ArrowDownToLine, ArrowUpFromLine,
  UserCircle, HardHat, Boxes, ScanBarcode, FileBarChart, Building2, Database, Calendar,
  Mail, MapPin, Check, CheckCircle2,
  type LucideProps,
} from 'lucide-react'

const ICON_MAP = {
  truck: Truck,
  smartphone: Smartphone,
  wallet: Wallet,
  satellite: Satellite,
  wrench: Wrench,
  'bar-chart': BarChart3,
  package: Package,
  container: Container,
  link: Link2,
  camera: Camera,
  landmark: Landmark,
  briefcase: Briefcase,
  shield: Shield,
  store: Store,
  fuel: Fuel,
  'file-text': FileText,
  banknote: Banknote,
  map: Map,
  'clipboard-list': ClipboardList,
  siren: Siren,
  'hand-heart': HandHeart,
  lamp: Lamp,
  coins: Coins,
  lock: Lock,
  clock: Clock,
  phone: Phone,
  users: Users,
  'credit-card': CreditCard,
  settings: Settings,
  route: Route,
  'trending-up': TrendingUp,
  handshake: Handshake,
  user: User,
  folder: FolderOpen,
  receipt: Receipt,
  'user-cog': UserCog,
  calculator: Calculator,
  sparkles: Sparkles,
  book: BookOpen,
  search: Search,
  'arrow-down': ArrowDownToLine,
  'arrow-up': ArrowUpFromLine,
  'user-circle': UserCircle,
  'hard-hat': HardHat,
  boxes: Boxes,
  'scan-barcode': ScanBarcode,
  'file-bar-chart': FileBarChart,
  'building-2': Building2,
  database: Database,
  calendar: Calendar,
  mail: Mail,
  'map-pin': MapPin,
  check: Check,
  'check-circle': CheckCircle2,
} as const

export type IconName = keyof typeof ICON_MAP

export function Icon({ name, ...props }: { name: IconName } & LucideProps) {
  const Component = ICON_MAP[name]
  return <Component {...props} />
}
